class SimpleCardAlphabet extends StandardId {
  public static readonly names = {
    markA: 'markA',
    markB: 'markB',
    markC: 'markC',
    markD: 'markD',
    markE: 'markE',
    markF: 'markF',
    markG: 'markG',
    markH: 'markH',
    markI: 'markI',
    markJ: 'markJ',
    markK: 'markK',
    markL: 'markL',
    markM: 'markM',
    markN: 'markN',
    markO: 'markO',
    markP: 'markP',
    markQ: 'markQ',
    markR: 'markR',
    markS: 'markS',
    markT: 'markT',
    markU: 'markU',
    markV: 'markV',
    markW: 'markW',
    markX: 'markX',
    markY: 'markY',
    markZ: 'markZ',
  };

  // Override
  public static readonly idTable = [
    { name: SimpleCardAlphabet.names.markA, id: 3670337 },
    { name: SimpleCardAlphabet.names.markB, id: 3670338 },
    { name: SimpleCardAlphabet.names.markC, id: 3670339 },
    { name: SimpleCardAlphabet.names.markD, id: 3670340 },
    { name: SimpleCardAlphabet.names.markE, id: 3670341 },
    { name: SimpleCardAlphabet.names.markF, id: 3670342 },
    { name: SimpleCardAlphabet.names.markG, id: 3670343 },
    { name: SimpleCardAlphabet.names.markH, id: 3670344 },
    { name: SimpleCardAlphabet.names.markI, id: 3670345 },
    { name: SimpleCardAlphabet.names.markJ, id: 3670346 },
    { name: SimpleCardAlphabet.names.markK, id: 3670347 },
    { name: SimpleCardAlphabet.names.markL, id: 3670348 },
    { name: SimpleCardAlphabet.names.markM, id: 3670349 },
    { name: SimpleCardAlphabet.names.markN, id: 3670350 },
    { name: SimpleCardAlphabet.names.markO, id: 3670351 },
    { name: SimpleCardAlphabet.names.markP, id: 3670352 },
    { name: SimpleCardAlphabet.names.markQ, id: 3670353 },
    { name: SimpleCardAlphabet.names.markR, id: 3670354 },
    { name: SimpleCardAlphabet.names.markS, id: 3670355 },
    { name: SimpleCardAlphabet.names.markT, id: 3670356 },
    { name: SimpleCardAlphabet.names.markU, id: 3670357 },
    { name: SimpleCardAlphabet.names.markV, id: 3670358 },
    { name: SimpleCardAlphabet.names.markW, id: 3670359 },
    { name: SimpleCardAlphabet.names.markX, id: 3670360 },
    { name: SimpleCardAlphabet.names.markY, id: 3670361 },
    { name: SimpleCardAlphabet.names.markZ, id: 3670362 },
  ];
}
