import { StandardId } from './standardId';

export class GameMark extends StandardId {
  public static readonly names = {
    craftFighter: 'craftFighter',
    rythmAndGo: 'rythmAndGo',
    skunkChaser: 'skunkChaser',
    fingerStrike2P: 'fingerStrike2P',
    fingerStrike1P: 'fingerStrike1P',
    freeMove: 'freeMove',
    quickSkunk2P: 'quickSkunk2P',
    quickSkunkCPU: 'quickSkunkCPU',
    KaijuBusters: 'KaijuBusters',
    watchOutFree: 'watchOutFree',
    watchOut2P: 'watchOut2P',
    watchOutCPU: 'watchOutCPU',
    colorMemory: 'colorMemory',
    lazerBeamChallenge: 'lazerBeamChallenge',
    lazerBeamCreate: 'lazerBeamCreate',
    Baton: 'Baton',
    pullBack: 'pullBack',
    dash: 'dash',
    dontDisturbNormal: 'dontDisturbNormal',
    dontDisturbRodeo: 'dontDisturbRodeo',
    answer: 'answer',
    music1: 'music1',
    music2: 'music2',
    music3: 'music3',
    music4: 'music4',
  };

  // Override
  public static readonly idTable = [
    { name: GameMark.names.craftFighter, id: 3670048 },
    { name: GameMark.names.rythmAndGo, id: 3670052 },
    { name: GameMark.names.skunkChaser, id: 3670086 },
    { name: GameMark.names.fingerStrike2P, id: 3670050 },
    { name: GameMark.names.fingerStrike1P, id: 3670088 },
    { name: GameMark.names.freeMove, id: 3670084 },
    { name: GameMark.names.quickSkunk2P, id: 3670092 },
    { name: GameMark.names.quickSkunkCPU, id: 3670094 },
    { name: GameMark.names.KaijuBusters, id: 3670096 },
    { name: GameMark.names.watchOutFree, id: 3670098 },
    { name: GameMark.names.watchOut2P, id: 3670100 },
    { name: GameMark.names.watchOutCPU, id: 3670102 },
    { name: GameMark.names.colorMemory, id: 3670104 },
    { name: GameMark.names.lazerBeamChallenge, id: 3670106 },
    { name: GameMark.names.lazerBeamCreate, id: 3670108 },
    { name: GameMark.names.Baton, id: 3670110 },
    { name: GameMark.names.pullBack, id: 3670112 },
    { name: GameMark.names.dash, id: 3670114 },
    { name: GameMark.names.dontDisturbNormal, id: 3670116 },
    { name: GameMark.names.dontDisturbRodeo, id: 3670118 },
    { name: GameMark.names.answer, id: 3670120 },
    { name: GameMark.names.music1, id: 3670122 },
    { name: GameMark.names.music2, id: 3670124 },
    { name: GameMark.names.music3, id: 3670126 },
    { name: GameMark.names.music4, id: 3670128 },
  ];
}
