# This is a basic workflow to help you get started with Actions

name: Build docs and website

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [12.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
#    - name: Installation
#      run: yarn
    - name: Website Installation
      run: cd website && yarn
#    - name: Generate TypeDoc
#      run: yarn docs2
    - name: Docusaurus Build
      run: cd website && yarn run build
      env:
        CI: true
